package main

import (
	caddycmd "github.com/caddyserver/caddy/v2/cmd"

	// plug in Caddy modules here
	_ "github.com/HeavenVolkoff/caddy-authelia/plugin"
	_ "github.com/WingLim/caddy-webhook"
	_ "github.com/abiosoft/caddy-exec"
	_ "github.com/abiosoft/caddy-hmac"
	_ "github.com/abiosoft/caddy-json-parse"
	_ "github.com/aksdb/caddy-cgi/v2"
	_ "github.com/baldinof/caddy-supervisor"
	_ "github.com/caddy-dns/alidns"
	_ "github.com/caddy-dns/azure"
	_ "github.com/caddy-dns/cloudflare"
	_ "github.com/caddy-dns/digitalocean"
	_ "github.com/caddy-dns/dnspod"
	_ "github.com/caddy-dns/duckdns"
	_ "github.com/caddy-dns/gandi"
	_ "github.com/caddy-dns/hetzner"
	_ "github.com/caddy-dns/openstack-designate"
	_ "github.com/caddy-dns/route53"
	_ "github.com/caddy-dns/vultr"
	_ "github.com/caddyserver/caddy/v2/modules/standard"
	_ "github.com/caddyserver/format-encoder"
	_ "github.com/caddyserver/ntlm-transport"
	_ "github.com/caddyserver/replace-response"
	_ "github.com/casbin/caddy-authz/v2"
	_ "github.com/cubic3d/caddy-ct"
	_ "github.com/cubic3d/caddy-quantity-limiter"
	_ "github.com/dunglas/mercure/caddy"
	_ "github.com/dunglas/vulcain/caddy"
	_ "github.com/gamalan/caddy-tlsredis"
	_ "github.com/ggicci/caddy-jwt"
	_ "github.com/greenpau/caddy-auth-portal"
	_ "github.com/greenpau/caddy-trace"
	_ "github.com/hslatman/caddy-crowdsec-bouncer/crowdsec"
	_ "github.com/hslatman/caddy-crowdsec-bouncer/http"
	_ "github.com/hslatman/caddy-crowdsec-bouncer/layer4"
	_ "github.com/kirsch33/realip"
	_ "github.com/lindenlab/caddy-s3-proxy"
	_ "github.com/lolPants/caddy-requestid"
	_ "github.com/mastercactapus/caddy2-proxyprotocol"
	_ "github.com/mholt/caddy-dynamicdns"
	_ "github.com/mholt/caddy-l4/layer4"
	_ "github.com/mholt/caddy-l4/modules/l4echo"
	_ "github.com/mholt/caddy-l4/modules/l4http"
	_ "github.com/mholt/caddy-l4/modules/l4proxy"
	_ "github.com/mholt/caddy-l4/modules/l4ssh"
	_ "github.com/mholt/caddy-l4/modules/l4tee"
	_ "github.com/mholt/caddy-l4/modules/l4tls"
	_ "github.com/mholt/caddy-ratelimit"
	_ "github.com/mholt/caddy-webdav"
	_ "github.com/porech/caddy-maxmind-geolocation"
	_ "github.com/pteich/caddy-tlsconsul"
	_ "github.com/silinternational/certmagic-storage-dynamodb/v2"
	_ "github.com/sjtug/caddy2-filter"
	_ "github.com/ss098/certmagic-s3"
	_ "github.com/ueffel/caddy-brotli"
	_ "magnax.ca/caddy/gopkg"
)

func main() {
	caddycmd.Main()
}
