package main

import (
	caddycmd "github.com/caddyserver/caddy/v2/cmd"

	// plug in Caddy modules here
	_ "github.com/Elegant996/scgi-transport"
	_ "github.com/HeavenVolkoff/caddy-authelia/plugin"
	_ "github.com/RussellLuo/caddy-ext/requestbodyvar"
	_ "github.com/RussellLuo/olaf/caddyconfig/adapter"
	_ "github.com/WingLim/caddy-webhook"
	_ "github.com/abiosoft/caddy-exec"
	_ "github.com/abiosoft/caddy-hmac"
	_ "github.com/abiosoft/caddy-json-parse"
	_ "github.com/abiosoft/caddy-json-schema"
	_ "github.com/abiosoft/caddy-named-routes"
	_ "github.com/abiosoft/caddy-yaml"
	_ "github.com/aksdb/caddy-cgi/v2"
	_ "github.com/baldinof/caddy-supervisor"
	_ "github.com/caddy-dns/alidns"
	_ "github.com/caddy-dns/azure"
	_ "github.com/caddy-dns/cloudflare"
	_ "github.com/caddy-dns/digitalocean"
	_ "github.com/caddy-dns/dnspod"
	_ "github.com/caddy-dns/duckdns"
	_ "github.com/caddy-dns/gandi"
	_ "github.com/caddy-dns/godaddy"
	_ "github.com/caddy-dns/googleclouddns"
	_ "github.com/caddy-dns/hetzner"
	_ "github.com/caddy-dns/lego-deprecated"
	_ "github.com/caddy-dns/metaname"
	_ "github.com/caddy-dns/netcup"
	_ "github.com/caddy-dns/netlify"
	_ "github.com/caddy-dns/openstack-designate"
	_ "github.com/caddy-dns/route53"
	_ "github.com/caddy-dns/vultr"
	_ "github.com/caddyserver/caddy/v2/modules/standard"
	_ "github.com/caddyserver/jsonc-adapter"
	_ "github.com/caddyserver/nginx-adapter"
	_ "github.com/caddyserver/ntlm-transport"
	_ "github.com/caddyserver/replace-response"
	_ "github.com/caddyserver/transform-encoder"
	_ "github.com/casbin/caddy-authz/v2"
	_ "github.com/chukmunnlee/caddy-openapi"
	_ "github.com/circa10a/caddy-geofence"
	_ "github.com/cubic3d/caddy-ct"
	_ "github.com/cubic3d/caddy-quantity-limiter"
	_ "github.com/darkweak/souin"
	_ "github.com/darkweak/souin/plugins/caddy"
	_ "github.com/gamalan/caddy-tlsredis"
	_ "github.com/gbox-proxy/gbox"
	_ "github.com/ggicci/caddy-jwt"
	_ "github.com/git001/caddyv2-upload"
	_ "github.com/greenpau/caddy-git"
	_ "github.com/greenpau/caddy-security"
	_ "github.com/greenpau/caddy-trace"
	_ "github.com/hairyhenderson/caddy-teapot-module"
	_ "github.com/hslatman/caddy-crowdsec-bouncer"
	_ "github.com/imgk/caddy-trojan"
	_ "github.com/kirsch33/realip"
	_ "github.com/lindenlab/caddy-s3-proxy"
	_ "github.com/lolPants/caddy-requestid"
	_ "github.com/lucaslorentz/caddy-docker-proxy/v2"
	_ "github.com/mastercactapus/caddy2-proxyprotocol"
	_ "github.com/mholt/caddy-dynamicdns"
	_ "github.com/mholt/caddy-l4"
	_ "github.com/mholt/caddy-ratelimit"
	_ "github.com/mholt/caddy-webdav"
	_ "github.com/mpilhlt/caddy-conneg"
	_ "github.com/muety/caddy-pirsch-plugin"
	_ "github.com/muety/caddy-remote-host"
	_ "github.com/porech/caddy-maxmind-geolocation"
	_ "github.com/pteich/caddy-tlsconsul"
	_ "github.com/shift72/caddy-geo-ip"
	_ "github.com/sillygod/cdp-cache"
	_ "github.com/sjtug/caddy2-filter"
	_ "github.com/techknowlogick/caddy-s3browser"
	_ "github.com/tosie/caddy-dns-linode"
	_ "github.com/ueffel/caddy-basic-auth-filter"
	_ "github.com/ueffel/caddy-brotli"
	_ "github.com/ueffel/caddy-imagefilter/defaults"
	_ "github.com/ueffel/caddy-tls-format"
	_ "magnax.ca/caddy/gopkg"
)

func main() {
	caddycmd.Main()
}
